### ISSUE TITLE
[.5] Python: Setup Typing

### ISSUE THREAD

**Issue by svix-frank** [svix/svix-libs#67] opened 2021-06-21 04:13 UTC
We should setup typing so that mypy can detect them

**Comment by tasn** [comment] 2021-06-21 07:40
Here's how I did it for python-ksuid:
https://github.com/svix/python-ksuid/commit/9277a3b8e435fa408f417503762b9000ac1d618c
https://github.com/svix/python-ksuid/commit/148285eaf2bc4b84f8a1ac99ccae6d7c96b253a6

**Comment by tasn** [comment] 2021-06-21 09:39
This is a duplicate of #52, though I'll close that one instead of this one as this one already has extra information. Please search existing issues before opening new ones.

**Closed** 2021-07-12 02:05 UTC
